.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CLI\-MAGIC" "1" "June 2018" "" ""
.
.SH "NAME"
\fBcli\-magic\fR \- an introduction to command line interfaces
.
.SH "SYNOPSIS"
wget \-O \- \-o /dev/null https://raw\.githubusercontent\.com/asciijungle/cli\-talk/master/cli\-magic\.7 | man /dev/stdin
.
.SH "DESCRIPTION"
This is an introduction to the command line interface (CLI) of modern unix operating systems\. It provides an overview about the terminology, as well as the history of CLIs and shows how to use the command line for productive day to day work\.
.
.SH "HISTORY"
In the middle of the last century, early computers had rather primitive input/output interfaces\. Both the program code and the input data were read from punch cards\. The output of the computation would then be printed onto paper by printers attached to the computer\.
.
.P
This was a batch process workflow rather than in interactive user session\. In order to facilitate a proper utilization of those very expensive early machines, jobs piled up and programmers had to wait for a long time before getting the results of their programms compilation and then its execution\.
.
.SS "Teletypewriter"
In 1956 scientists at MIT were experimenting with attaching a teletypewriter to a computer to unify input and output\. Even before the invention of the computer teletypewriters have been used for communication replacing the morse code based telegraphy\.
.
.SS "Visual Display Units (glass TTY)"
.
.SS "Terminal Emulators"
different escape sequences
.
.SS "Control Codes"
\fICtrl\-C\fR
.
.P
You can use Ctrl\-C in your terminal to abort a running program\. This sends a SIGINT signal to the process currently executed by the shell\. Most programs interpret it similar to SIGTERM wich calls for graceful termination\.
.
.P
\fICtrl\-D\fR
.
.P
Ctrl\-D sends an end of line (EOL) character to the shell\. The shell interprets end of line as the end of user input\. It therefore has the same result as typing exit in the shell\.
.
.P
\fICtrl\-U\fR
.
.P
Ctrl\-U cancels the currently inputted command line\.
.
.P
\fICtrl\-K\fR
.
.P
Ctrl\-K cancels user input from the location of the cursor to the end of the line\.
.
.P
\fICtrl\-Z\fR
.
.P
Pause the currently executed program and return to the shell\. You can resume stopped processes with \fBfg\fR or \fBbg\fR\.
.
.P
\fICtrl\-R\fR
.
.P
triggers reverse search through the command line history\.
.
.P
\fICtrl\-L\fR
.
.P
Clears the current content of the terminal starting with a clean prompt\.
.
.SH "SHELL"
The Shell is the program directly connected to a terminal\. It provides an interactive programming language allowing you to invoke different programs as well as combining them to accomplish a certain outcome\. The difference between the shell and other interpreted programming languages like e\.g\. python is that in python most of the code is written to be run in the interpreter itself, whereas the shell is primarily starting other programs to do the work\.
.
.SS "Prompt"
The prompt is shown to indicate that the shell is ready for receiving input\. It can be customized via the $PS1 variable\. In your shell configuration you can do fancy stuff like calling programms and adding their output to the prompt\.
.
.SS "current working directory"
There is always a current working directory from which relative paths will be interpreted\. You can show the current working directory with the \fBpwd\fR command\.
.
.SS "Variables and Environment Variables"
\fIPATH\fR
.
.P
The path variable defines directories where the shell looks for executables that are directly known to the shell\.
.
.SS "piping"
You can combine various commands with the \fB|\fR pipe operator\. The output of the first command (Stdout) will be fed into the input (Stdin) of the second command\. For example: ls | less
.
.SH "process substitution"
Process substitution allows a process\'s input or output to be referred to using a filename\. It takes the form of \fI(list) or\fR(list)\. The process list is run asynchronously, and its input or output appears as a filename\. This is a bit like piping into files\.
.
.SS "brace expension"
~/dev/customer1/{repo1, repo2}
.
.P
/home/bbr/dev/customer1/repo1 /home/bbr/dev/customer1/repo2
.
.SS "History"
The Shell writes all executed commands into a history file which is shell specific\. For bash it is ~/\.bash_history\. You can browse the history via the \fBhistory\fR command\. You can also browse the last commands via arrow up, arow down\. Remember: you can also search the history in reverse via CTRL\-R\.
.
.SS "Tab completion"
The shell has a lot of convenience functions\. One of them is the tab completion feature\. At almost any time you can complete using tab\. This depends on the program and the shell implementation\. You should look into ZSH if you want advanced tab completion\.
.
.SH "Aliases"
You can define command aliases in your shell\'s config file to define shortcuts\. For bash thats ~/\.bashrc
.
.SH "PROGRAMMS"
Unix comes with a lot of utility programs that you can combine to write shell scripts\.
.
.SS "man"
Shows the manual of a given program\. This talk is a man page too ;)
.
.SS "grep"
grep searches stdin for a given string\. grep \-r can search recursively in all files in a directory\.
.
.SS "less"
a pager that allows you to scroll an input in both ways\. It also provides a search functionality\.
.
.SS "sed"
sed is the "stream editor" it allows for advanced manipulation of the input stream\.
.
.SS "awk"
pattern scanning and processing language\. You can do advanced stuff with table shaped data\.
.
.SS "uniq"
remove or count redundant lines in a sorted input stream\.
.
.SS "sort"
sorts a stream in various ways\.
.
.SH "Terminal multiplexing"
.
.SS "tmux"
.
.SS "screen"
.
.SH "AUTHOR"
Benjamin Brunzel \fIbenjamin\.brunzel@iteratec\.de\fR Harald Berner \fIharald\.berner@iteratec\.de\fR
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
In depth video lecture to the Unix command line: https://www\.youtube\.com/watch?v=07Q9oqNLXB4
.
.IP "\(bu" 4
Video showing the compilation workflow of a \fBFortran\fR programm on an IBM 1401: https://www\.youtube\.com/watch?v=uFQ3sajIdaM
.
.IP "\(bu" 4
Time sharing concept and hard copy terminals (1963) https://www\.youtube\.com/watch?v=Q07PhW5sCEk
.
.IP "\(bu" 4
see introduction to the Unix operating system (1982) https://www\.youtube\.com/watch?v=tc4ROCJYbm0
.
.IP "\(bu" 4
List of terminal control codes available in \fBbash\fR: http://wiki\.bash\-hackers\.org/scripting/terminalcodes
.
.IP "" 0

